### ISSUE TITLE
On going to background or app switcher on Android the popup appears

### ISSUE THREAD

**Issue by Zakyyy** [calintamas/react-native-toast-message#300]
**Describe the bug**
On Android when I go to background or to the app switcher the pop up appears without calling it

**Steps to reproduce**
1. Go to Background/Appswitcher
2. The toast will appear

**Expected behavior**
Nothing to show unless I call it

**Environment (please complete the following information):**
 - OS: Android
 - react-native-toast-message version: v2.1.1
 - react-native version v0.66.1

**Comment by tapz** [comment]
When my app asks mic permissions after app has been started an empty toast is displayed until the permission popups disappear. Why can't the toast be created to be out of the screen?

**Comment by hirbod** [comment]
I can confirm that this is also happening for me in expo-dev-client.
As soon as I open the app switcher, it appears (and even freezes in place when I receive an SMS for example)

**Comment by IngyuTae** [comment]
Same here. Any update on this issue?

**Comment by urrvesh** [comment]
const config: ConfigParams = {
  success: (props) => {
  return **props.isVisible** ? <Component /> : null
  },
};

<Toast
    position={'bottom'}
    config={config}
/>

props.isVisible should work here. Working fine for me. Thanks

**Comment by mikicnemanjaeyc** [comment]
> `const config = { success: (props) => { return props.isVisible ? <Component /> : null } };`
> 
> <Toast position={'bottom'} config={config} />
> 
> props.isVisible should work here. Working fine for me. Thanks

Thank you for this workaround

**Comment by vasylnahuliak** [comment]
> Moving the `<Toast config={toastConfig}/>` up in the App.js component hierarchy fixed this issue for me

`Toast` does not work for me if it is higher in the hierarchy than the navigation.

Could you show your App.js?

**Comment by mikicnemanjaeyc** [comment]
@vasylnahuliak you are right, lol
I updated the default success modal that is being displayed: `export default toastConfig = {
  success: () => <></>,
};` , masking it so its not visible

**Comment by cardiffinc** [comment]
Is there any update on this? 
I'm facing the same issue and re-production steps is similar to comment#1

**Comment by ashish293** [comment]
> `const config = { success: (props) => { return props.isVisible ? <Component /> : null } };`
> 
> <Toast position={'bottom'} config={config} />
> 
> props.isVisible should work here. Working fine for me. Thanks

This Worked for my Thanks

**Comment by hirbod** [comment]
@calintamas I'll set a bounty of 50 USD if you fix this properly at the root (without any weird `null` hacks)
If it's fixed until Saturday, I'll increase it to 100 USD.

Whoever fix this correct first, gets the bounty!

**Comment by hirbod** [comment]
@TheSteveHan thanks for pointing that out. I still feel like disabling the native driver is not a real solution, but I might end up to patch this platform based for android only.

**Comment by calintamas** [comment]
I also started looking into it during the weekend. Main issue is that I can't reproduce locally, but I think @TheSteveHan's solution can be a good-enough workaround for now. I'm close to exposing `useNativeDriver` as a prop to the Toast instance, just need to wrap a few things up

**Comment by TheSteveHan** [comment]
The issue doesn't occur in the emulator for me. I'm seeing this issue on 2 samsung android devices running Android 12 and Android 11. However, I couldn't reproduce the issue on emulator either. Disabling useNativeDriver resolved the issue for me on both devices.

**Comment by tapz** [comment]
One way to reproduce this is to ask some permission in the native code when the app has started. This freezes the toast until the user has given the permission.

**Comment by TheSteveHan** [comment]
> disabling the native driver is not a real solution
Since there's no performance concern here really, is using the native driver really a requirement? 

If using the native driver is a hard requirement, perhaps the solution might have to be something like moving the default state of the toast off of the screen and animate it in so that when the animation system is reset the toast is hidden?

**Comment by tapz** [comment]
I agree with @TheSteveHan that the toast should initially be placed outside of the screen and then transformed to the screen using the animations.

**Comment by calintamas** [comment]
I think setting up the initial position outside the screen can be the solution indeed. 

I published it as `v2.2.0-beta2`, please install it and see if it fixes the issue.

```sh
yarn add react-native-toast-message@v2.2.0-beta2
```

**Comment by calintamas** [comment]
Was anyone able to test it?

**Comment by hirbod** [comment]
@calintamas I tried it. It is still flashing for a moment and disappears after. I would not call it fixed

**Comment by wouterds** [comment]
Confirmed it still occurs on 2.2.0-beta2. When exiting the app by clicking the home button a toast will temporarily popup.

**Comment by AndreiBacescu** [comment]
> @urrvesh thats not a good workaround unfortunately, since it breaks the hide animation on iOS.


Is not only iOS but Android too.

**Comment by ZohaibNaseer786** [comment]
Add `isVisible` in this file `src/components/AnimatedContainer`

```
 return (
    isVisible && ( //  <---- add here
      <Animated.View
        testID={getTestId("AnimatedContainer")}
        onLayout={computeViewDimensions}
        style={[styles.base, styles[position], animationStyles]}
        // This container View is never the target of touch events but its subviews can be.
        // By doing this, tapping buttons behind the Toast is allowed
        pointerEvents={isVisible ? "box-none" : "none"}
        {...panResponder.panHandlers}
      >
        {children}
      </Animated.View>
    )
  );
```

**Comment by HyopeR** [comment]
Hello, I have this problem too. I have an application with universal link support. I am encountering this problem in the following scenario.

```bash
"react-native-toast-message": "2.1.6",
```

**1-** A URL address is sent to the user to open it in the application.
**2-** The user opens the application by clicking on a URL address such as https://example.com.
**3-** After the application is opened, the react-native-toast-message component appears and disappears momentarily.

For those looking for a **temporary and easy solution**, this is what I do. The problem I encountered here was simply that the first component was automatically shown when the application was first loaded. This issue seems to be temporarily resolved when I replace the first component with an empty component.

```js
<NavigationContainer>
  <Toast
    type={'none'}
    config={{
      none: ({...rest}) => <></>,
      success: ({...rest}) => <AuPrettyToast icon={'CheckmarkCircle'} {...rest} />,
      info: ({...rest}) => <AuPrettyToast icon={'InformationCircle'} {...rest} />,
      warning: ({...rest}) => <AuPrettyToast icon={'AlertCircle'} {...rest} />,
      error: ({...rest}) => <AuPrettyToast icon={'CloseCircle'} {...rest} />,
      basic: ({...rest}) => <AuBasicToast {...rest} />,
    }}
  />
</NavigationContainer>
```

**Comment by calintamas** [comment]
Released a fix in [v2.2.1](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.2.1)
